// console.log ("Hello World")

// IDEA: Write a function which receives a whole number and returns a string...

// IF THE NUMBER IS EVEN THE STRING SHOULD BE "EVEN"
// IF THE NUMBER IS ODD                       "ODD"
// IF A MULTIPLE OF 5 THE STRING SHOULD BE "ODDFIVER" OR "EVENFIVER"  DEPENDING ON WHETHER IT IS ODD OR EVEN

// SUDO CODE
// FUNCTION NAMED "FIVER"
// INPUT - AN INTEGER
// OUTPUT - A STRING - EITHER ODD, ODD FIVER, EVEN, OR EVEN FIVER

// CONDITIONS - IF NUMBER IS EVEN
// RESEARCH  -  HOW TO CHECK IF A NUMBER IS EVEN
// "EVEN"

// IF THE NUMBER IS ODD - OPPOSITE OF EVEN
// "ODD"

// IF NUMBER IS MULTIPLE OF 5 AND IS ODD 
// RESEARCH - HOW TO CHECK IF A MULTIPLE OF 5
// RETURN EVENFIVER OR ODDFIVER DEPENDING ON WEATHER ITS EVEN OR ODD.

function fiver(params) {
    
}